#!/usr/bin/env bash
# Generate the theme×style gallery for the promo page straight from the binary.
# Output: inline HTML cards injected into docs/index.html between GALLERY markers.
# Re-running is deterministic (themes/styles come from `claudebar list`).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="${CLAUDEBAR_BIN:-$ROOT/target/release/claudebar}"
SAMPLE="$ROOT/docs/assets/sample-session.json"
INDEX="$ROOT/docs/index.html"
A2H="$ROOT/scripts/ansi2html.py"

[ -x "$BIN" ] || { echo "ERROR: binary not found at $BIN (run: cargo build --release)" >&2; exit 1; }
[ -f "$SAMPLE" ] || { echo "ERROR: sample session missing: $SAMPLE" >&2; exit 1; }

mapfile -t THEMES < <("$BIN" list | awk '/^Themes:/{f=1;next} /^Styles:/{f=0} f && NF {gsub(/^ +/,"");print}')
mapfile -t STYLES < <("$BIN" list | awk '/^Styles:/{f=1;next} f && NF {gsub(/^ +/,"");print}')

[ "${#THEMES[@]}" -gt 0 ] || { echo "ERROR: no themes parsed from \`$BIN list\`" >&2; exit 1; }
[ "${#STYLES[@]}" -gt 0 ] || { echo "ERROR: no styles parsed from \`$BIN list\`" >&2; exit 1; }

FRAG="$(mktemp)"
echo '<div class="gallery-grid" id="gallery-grid">' >> "$FRAG"
count=0
for t in "${THEMES[@]}"; do
  for s in "${STYLES[@]}"; do
    strip_html="$("$BIN" render --theme "$t" --style "$s" < "$SAMPLE" | python3 "$A2H")"
    {
      printf '  <figure>\n'
      printf '    <figcaption>%s · %s</figcaption>\n' "$t" "$s"
      printf '    <div class="strip">%s</div>\n' "$strip_html"
      printf '  </figure>\n'
    } >> "$FRAG"
    count=$((count + 1))
  done
done
echo '</div>' >> "$FRAG"

# Replace everything between the GALLERY markers in index.html with the fragment.
python3 - "$INDEX" "$FRAG" <<'PY'
import sys, re
index, frag = sys.argv[1], sys.argv[2]
html = open(index, encoding="utf-8").read()
new = open(frag, encoding="utf-8").read().rstrip("\n")
start = "<!-- GALLERY:START (generated by scripts/gen-gallery.sh — do not edit by hand) -->"
end = "<!-- GALLERY:END -->"
pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
repl = start + "\n" + new + "\n      " + end
html2, n = pat.subn(repl, html)
if n != 1:
    sys.exit(f"ERROR: expected 1 gallery marker block, found {n}")
open(index, "w", encoding="utf-8").write(html2)
PY
rm -f "$FRAG"
echo "Gallery: ${#THEMES[@]} themes × ${#STYLES[@]} styles = $count cards → $INDEX"
